hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2500
hystrix.command.organization.execution.isolation.thread.timeoutInMilliseconds: 3000
server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: organization-service
          uri: lb://organization-service/
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
            - Path=/licensing/**
          filters:
            - RewritePath=/licensing/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: info

